version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: changeMe!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  gateway:
    build: ./gateway
    depends_on:
      - auth-service
      - transaction-service
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis

  auth-service:
    build: ./auth-service
    depends_on:
      postgres:
        condition: service_healthy
      - redis
    ports:
      - "8081:8081"

  transaction-service:
    build: ./transaction-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"

  audit-service:
    build: ./audit-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8083:8083"

  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  pgdata: {}


