server:
  port: 8083

spring:
  application:
    name: audit-service
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: c2VjdXJlLXN1cGVyLXNlY3JldC1kZW1vLXNob3VsZC1iZS0zMi1ieXRlcy1vci1sb25nZXI=
  datasource:
    url: jdbc:postgresql://postgres:5432/hoardrun_audit
    username: audit_user
    password: changeMe
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
