global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['gateway:8080']
  - job_name: 'auth-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['auth-service:8081']
  - job_name: 'transaction-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['transaction-service:8082']
  - job_name: 'audit-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['audit-service:8083']


