name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-
      - name: Build with Maven
        run: mvn -DskipTests package
      - name: Build Docker images
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push services
        if: github.event_name == 'push'
        run: |
          docker build -t ghcr.io/${{ github.repository }}/gateway:latest gateway
          docker build -t ghcr.io/${{ github.repository }}/auth-service:latest auth-service
          docker build -t ghcr.io/${{ github.repository }}/transaction-service:latest transaction-service
          docker build -t ghcr.io/${{ github.repository }}/audit-service:latest audit-service
          docker push ghcr.io/${{ github.repository }}/gateway:latest
          docker push ghcr.io/${{ github.repository }}/auth-service:latest
          docker push ghcr.io/${{ github.repository }}/transaction-service:latest
          docker push ghcr.io/${{ github.repository }}/audit-service:latest


